parameters:
    hgabka_pagepart.page_part_configuration_reader.class: 'Hgabka\PagePartBundle\PagePartConfigurationReader\PagePartConfigurationReader'
    hgabka_pagepart.page_part_configuration_parser.class: 'Hgabka\PagePartBundle\PagePartConfigurationReader\PagePartConfigurationParser'

    hgabka_pagepart.page_template_configuration_reader.class: 'Hgabka\PagePartBundle\PageTemplate\PageTemplateConfigurationReader'
    hgabka_pagepart.page_template_configuration_parser.class: 'Hgabka\PagePartBundle\PageTemplate\PageTemplateConfigurationParser'

    hgabka_page_part.page_template.page_template_configuration_service.class: 'Hgabka\PagePartBundle\PageTemplate\PageTemplateConfigurationService'

services:
    hgabka_pagepart.pageparts:
        class: 'Hgabka\PagePartBundle\PagePartAdmin\Builder'

    Hgabka\PagePartBundle\PagePartConfigurationReader\PagePartConfigurationReader:
        public: true
        arguments: [ '@hgabka_page_part.page_part_configuration_parser' ]

    hgabka_page_part.page_part_configuration_reader:
        alias: Hgabka\PagePartBundle\PagePartConfigurationReader\PagePartConfigurationReader

    hgabka_page_part.page_part_configuration_parser:
        class: '%hgabka_pagepart.page_part_configuration_parser.class%'
        public: false
        arguments: [ '@kernel', '%hgabka_page_part.page_parts_presets%' ]

    hgabka_page_part.page_template_configuration_reader:
        class: '%hgabka_pagepart.page_template_configuration_reader.class%'
        arguments: [ '@hgabka_page_part.page_template_configuration_parser' ]

    hgabka_page_part.page_template_configuration_parser:
        class: '%hgabka_pagepart.page_template_configuration_parser.class%'
        public: false
        arguments: [ '@kernel', '%hgabka_page_part.page_templates_presets%' ]


    hgabka_page_part.page_template.page_template_configuration_service:
        class: '%hgabka_page_part.page_template.page_template_configuration_service.class%'
        arguments:
          - '@hgabka_page_part.repository.page_template_configuration'
          - '@hgabka_page_part.page_template_configuration_reader'

    hgabka_page_part.repository.page_template_configuration:
        class: 'Hgabka\PagePartBundle\Repository\PageTemplateConfigurationRepository'
        public: false
        factory: [ '@doctrine.orm.entity_manager', 'getRepository' ]
        arguments:
          - 'HgabkaPagePartBundle:PageTemplateConfiguration'

    hgabka_pagepartadmin.factory:
        class: 'Hgabka\PagePartBundle\PagePartAdmin\PagePartAdminFactory'
        arguments: ['@service_container']

    hgabka_pagepartadmin.twig.extension:
        class: 'Hgabka\PagePartBundle\Twig\Extension\PagePartAdminTwigExtension'
        tags:
            -  { name: twig.extension }
        calls:
            - [ setUsesExtendedPagePartChooser, [ '%hgabka_page_part.extended%' ] ]

    hgabka_pageparts.twig.extension:
        class: 'Hgabka\PagePartBundle\Twig\Extension\PagePartTwigExtension'
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: twig.extension }

    hgabka_pagetemplate.twig.extension:
        class: 'Hgabka\PagePartBundle\Twig\Extension\PageTemplateTwigExtension'
        arguments:
            - '@hgabka_page_part.page_template.page_template_configuration_service'
        tags:
            - { name: twig.extension }

    hgabka_pageparts.pagepart_creator_service:
        class: 'Hgabka\PagePartBundle\Helper\Services\PagePartCreatorService'
        calls:
            - [ setEntityManager, [ '@doctrine.orm.entity_manager' ] ]

    hgabka_pageparts.edit_node.listener:
        class: 'Hgabka\PagePartBundle\EventListener\NodeListener'
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@hgabka_pagepartadmin.factory'
          - '@hgabka_page_part.page_template_configuration_reader'
          - '@hgabka_page_part.page_part_configuration_reader'
          - '@hgabka_page_part.page_template.page_template_configuration_service'
        tags:
            - { name: kernel.event_listener, event: hgabka_node.adaptForm, method: adaptForm }

    hgabka_pageparts.clone.listener:
        class: 'Hgabka\PagePartBundle\EventListener\CloneListener'
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@hgabka_page_part.page_part_configuration_reader'
          - '@hgabka_page_part.page_template.page_template_configuration_service'

        tags:
            - { name: kernel.event_listener, event: hgabka_utils.postDeepCloneAndSave, method: postDeepCloneAndSave }
